### ISSUE TITLE
Reference use of DID Document Metadata properties in specification

### ISSUE THREAD

**Issue by frankhinek** [decentralized-identity/did-dht#120]
Proposal to update the DID DHT specification to reference use of the [`versionId`](https://www.w3.org/TR/did-core/#dfn-versionid) DID Document Metadata property to store the sequence number in Mainline DHT.

If we standardize on using Unix Epoch Time seconds for the sequence number, it would also be easy to have a verifiable value for:
- [`created`](https://www.w3.org/TR/did-core/#dfn-created)
- [`updated`](https://www.w3.org/TR/did-core/#dfn-updated)

We should also note that resolvers should return the [`deactivated`](https://www.w3.org/TR/did-core/#dfn-deactivated) property set to `true` after the root DNS record with the string “deactivated” has been published.

**Comment by thereisnogabe** [comment]
Agree and agree.
