### ISSUE TITLE
Should be able to configure and disable telemetry

### ISSUE THREAD

**Issue by dmidnight** [decentralized-identity/did-dht#164]
**Describe the bug**

When I start a DHT Gateway, the logs are full of lines like this

```2024-04-04 12:00:00.153 EDT
2024/04/04 16:00:00 traces export: Post "https://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused

2024-04-04 12:00:03.627 EDT
2024/04/04 16:00:03 failed to upload metrics: Post "https://localhost:4318/v1/metrics": dial tcp 127.0.0.1:4318: connect: connection refused
```

**To Reproduce:**
*Steps to reproduce the behavior:*
1. Build the docker image
2. Run it 

**Expected behavior:**
*A clear and concise description of what you expected to happen.*

Expect to be able to configure a different Url for telemetry, or just turn it off

**Supporting Material**
*If applicable, add screenshots, output log and/or other documentation to help explain your problem.*

**Environment (please complete the following information):**
 - docker container on Kubernetes

**Additional context**
Add any other context that you feel is relevant about the problem here.

**Comment by thereisnogabe** [comment]
have added the ability to turn it off
