### ISSUE TITLE
Handling key references within the DID Document

### ISSUE THREAD

**Issue by thereisnogabe** [decentralized-identity/did-dht#224]
Since #209 we remove the ability to specify a custom ID for Verification Methods. This was motivated by a few factors:

1. We can deterministically calculate a Verification Method's ID (VMIDs) using the JWK Thumbprint, since we require usage of JWKs. For the Identity Key the ID is set to `0` which is also deterministic.
2. We save bytes in the DHT payload by removing the ID entirely.
3. We simplify implementations needing to handle a mix of cases (whether there's an ID, whether it matches the JWK KID, whether it's a thumbprint).

There is a use case we did not fully consider, which is when other properties in the DID Document need to reference VMIDs. This is no elegant way to do this today -- the best we can do is say refer to the thumbprint as the VMID. This requires using up those bytes we were trying to save, which is not ideal.

As a path forward we have a few potential options:
1. Change nothing — reference VMIDs by thumbprints should you need to.
2. Add back custom VM IDs as an optional feature (noting complexity and size concerns from above)
3. Add a special syntax to reference VMIDs without needing to have the full thumbprint. For example instead of requiring the thumbprint directly use the DNS packet reference such as `k0` or `k1`.

There may be other options I haven't thought of yet too.

---------------------------------------------------------------

FWIW I ran the ideas by Claude who suggested option (3), which included some good reasoning, with my favorite being:
> Introducing a new syntax for referencing VMIDs should not break existing implementations or cause compatibility issues. It can be added as a new feature without disrupting the current functionality.

**Comment by thereisnogabe** [comment]
cc: @LiranCohen @csuwildcat @frankhinek @thehenrytsai

**Comment by frankhinek** [comment]
I suppose Option 3 does have the complexity that when creating a new DID you won't know the VM ID's nor the DNS packet reference so you'd have to create the DID without the service first and then add in the service, correct?

**Comment by LiranCohen** [comment]
I personally prefer Option 2 for the sake of simplicity and giving the creator of the document that optionality.

If we were to go with Option 3, it wouldn't be only `did:dht` specific, we'd probably have to generalize that as a standard across all of our DID create methods, correct?

**Comment by frankhinek** [comment]
> If we were to go with Option 3, it wouldn't be only did:dht specific, we'd probably have to generalize that as a standard across all of our DID create methods, correct?

That is a good consideration to keep in mind.  Ideally the `create` operation for DID DHT isn't significantly different than other DID methods that support `service` entries.

**Comment by thereisnogabe** [comment]
> I suppose Option 3 does have the complexity that when creating a new DID you won't know the VM ID's nor the DNS packet reference so you'd have to create the DID without the service first and then add in the service, correct?

This depends on the implementation entirely. There could be a function that abstracts this complexity and makes sure to only call the network once after the document is fully assembled.

**Comment by thereisnogabe** [comment]
> > If we were to go with Option 3, it wouldn't be only did:dht specific, we'd probably have to generalize that as a standard across all of our DID create methods, correct?
> 
> That is a good consideration to keep in mind. Ideally the `create` operation for DID DHT isn't significantly different than other DID methods that support `service` entries.

All DID methods have a set of properties unique to them. DID JWK doesn't have a publish method, DID DHT does. DID DHT doesn't support recovery, DID ION does. These could be passed in as a set of method-specific options to a generic 'create DID' interface.

**Comment by thehenrytsai** [comment]
I vote for option 2* where user specified ID is the only support path, ASSUMING this would cut down complexity further so that: 

1. Users only have one (no) choice.
1. Implementor only needs implement one path.

**Comment by thereisnogabe** [comment]
I want to re-emphasize that this is only for the case of referencing VMIDs from other properties in the DID Document. I'm not clear how common a practice is, or whether we should change the method to accommodate an edge case that adds in other complexities. 

@thehenrytsai your 2* option guarantees that every DNS packet will have an increase in size compared to today's implementation, which seems like a non-starter.

-------------------

Here is Claude's full reasoning for 3:

Option 3 (adding a special syntax to reference VMIDs) strikes a good balance between saving bytes, simplifying implementations, and enabling the referencing of VMIDs within the DID Document.

Here's why I believe option 3 is the best solution:

**Saving bytes:** By using a compact syntax like k0 or k1 to reference VMIDs, you can avoid the overhead of including the full JWK thumbprint in the DID Document. This aligns with your goal of minimizing the payload size in the DHT.

**Simplifying implementations:** With a consistent and predictable syntax for referencing VMIDs, implementations can easily handle the referencing without needing to deal with different cases or variations. This simplifies the code and reduces the potential for errors or inconsistencies.

**Enabling VMID referencing:** The special syntax allows other properties in the DID Document to reference VMIDs without the need for including the full thumbprint. This addresses the use case you mentioned where referencing VMIDs is necessary.

**Maintaining determinism:** By using a deterministic syntax like k0 or k1, you can still maintain the deterministic nature of VMIDs. The mapping between the special syntax and the actual VMID (JWK thumbprint) can be clearly defined in the specification.

**Compatibility:** Introducing a new syntax for referencing VMIDs should not break existing implementations or cause compatibility issues. It can be added as a new feature without disrupting the current functionality.

**Comment by LiranCohen** [comment]
Maybe my understanding/reasoning behind Option 3 is incorrect.

But If I wanted to keep a uniform `CreateOptions` for a `[anyDIDMethod].create()` method within our libs, all of the implementations for the other DID methods within our libs would also need to follow this key-reference scheme, correct?

**Comment by thereisnogabe** [comment]
> But If I wanted to keep a uniform `CreateOptions` for a `[anyDIDMethod].create()` method within our libs, all of the implementations for the other DID methods within our libs would also need to follow this key-reference scheme, correct?

No not at all. This only applies to the DNS packet representation of DID Docs, which only applies to DID DHT. It's a method specific option

**Comment by LiranCohen** [comment]
Yeah I'm definitely not following. Maybe a concrete example helps.

Currently `DidOptions` looks something like this:

```
didOptions : {
        services: [
          {
            id              : 'dwn',
            type            : 'DecentralizedWebNode',
            serviceEndpoint : testDwnUrls,
            enc             : '#enc',
            sig             : '#sig',
          }
        ],
        verificationMethods: [
          {
            algorithm : 'Ed25519',
            id        : 'sig',
            purposes  : ['assertionMethod', 'authentication']
          },
          {
            algorithm : 'secp256k1',
            id        : 'enc',
            purposes  : ['keyAgreement']
          }
        ]
      },
```

Would `did:dht` still take those same options but know to replace `#enc` and `#sig` with the thumbprint because the fragments map to an existing `VM` within the options? And then other methods would just do the normal referencing that exists today?

**Comment by thereisnogabe** [comment]
That's one possibility. 

We could introduce a new DIDDHTOptions that does not allow specification of VMIDs. Enc and Sig values can use a special syntax like (k0, k1) such as

```
didOptions : {
        services: [
          {
            id              : 'dwn',
            type            : 'DecentralizedWebNode',
            serviceEndpoint : testDwnUrls,
            enc             : 'k1',
            sig             : 'k2',
          }
        ],
        verificationMethods: [
          {
            algorithm : 'Ed25519',
            purposes  : ['assertionMethod', 'authentication']
          },
          {
            algorithm : 'secp256k1',
            purposes  : ['keyAgreement']
          }
        ]
      },
```

or have a method that does something similar to what @frankhinek suggested above: 
1. create the DID Doc without services
2. create the services using the DNS packet representation key references (k1, k2)

either way there needs to be some logic in the DID Doc -> DNS Packet function that is able to pick up 'k1' or 'k2' and expand

**Comment by csuwildcat** [comment]
I think Liran is saying that it's bad for a method's input params to expose method specific DSLs if it can be avoided. (I agree, if that's the crux of it) 

> > But If I wanted to keep a uniform `CreateOptions` for a `[anyDIDMethod].create()` method within our libs, all of the implementations for the other DID methods within our libs would also need to follow this key-reference scheme, correct?
> 
> No not at all. This only applies to the DNS packet representation of DID Docs, which only applies to DID DHT. It's a method specific option

**Comment by LiranCohen** [comment]
> I think Liran is saying that it's bad for a method's input params to expose method specific DSLs if it can be avoided. (I agree, if that's the crux of it)

Yeah basically either way we slice it, we'd *like* for the DID Create options to be uniform.

**Comment by thereisnogabe** [comment]
it's unavoidable

1. methods have features/properties that are unique
2. they have options that enable configuring those unique features/properties

it is also a layer violation to dictate an implementation detail of the DNS packet representation of a DID Document from an SDK's abstraction (interface) over creating DIDs for multiple methods. Forcing all DID methods to conform to a generic set of options would hinder the flexibility and extensibility of the DID system.

**Comment by LiranCohen** [comment]
> it's unavoidable
> 
> 1. methods have features/properties that are unique
> 2. they have options that enable configuring those unique features/properties
> 
> it is also a layer violation to dictate an implementation detail of the DNS packet representation of a DID Document from an SDK's abstraction (interface) over creating DIDs for multiple methods. Forcing all DID methods to conform to a generic set of options would hinder the flexibility and extensibility of the DID system.

I generally don't disagree with both points.

I think we have to think about and decide on how our libraries create/manage DIDs, are we going to keep a Universal Resolver class for resolving all DIDs, but get rid of any generic `DidApi.create()` library?

I'm less familiar with the other SDKs we have created, do they attempt to also conform to a single API method for creating a DID the way `@web5/dids` does?

**Comment by thereisnogabe** [comment]
each method can (and does) have unique options for create, so a generic create is still on the table
here's an example with the DIF universal registrar - https://uniregistrar.io/

**Comment by LiranCohen** [comment]
Yeah I know it's technically the case, but for DevEx how do we want our libs and options to be?

**Comment by csuwildcat** [comment]
So are we re-enabling setting key IDs? I really think that's for the best, because it's simple and what appears to be the most expected behavior across most DID methods.

**Comment by thereisnogabe** [comment]
@csuwildcat yes after consideration I agree option 2 is best

I will put out a PR and tag you all later today

**Comment by LiranCohen** [comment]
Hey @decentralgabe wanted to confirm the track we are on for this.

The goal is to make the `keyId` optional, if it is provided then that is what will be used, otherwise the key fingerprint will be derived and used.

Would the goal with the test vectors be for vector 3 to add a 3rd JWK with a named `kid`?
Also, would there be any string length limitations for the user-specified `kid`?

Want to get a leg-up on this on the `@web5/dids` package, let me know if you need any assistance w/ the spec or adding to the vectors.

**Comment by thereisnogabe** [comment]
That sounds right the restriction I had in mind would be to limit the kid to 10 characters - but I pulled that out of nowhere so open to suggestions

**Comment by thehenrytsai** [comment]
May I suggest a vector 4 or put it in vector 1 or 2 for this because:
1. There are already plenty variability for vector 3 (`prv`, `X25519`, chunked data, multiple authoritative gateways etc), adding more just makes it that much more painful for an implementor.
1. I am implementing vector 3 compliance as we speak, with it being in a different vector than 3, or a working vector (1, 2), you can write a passing test vector test without depending on me.

**Comment by thereisnogabe** [comment]
@thehenrytsai yes I will either introduce a new vector or amend 1/2
