### ISSUE TITLE
Consider compressing the DNS packet before bencoding

### ISSUE THREAD

**Issue by andresuribe87** [decentralized-identity/did-dht#34]
The spec currently reads

> Construct a signed [BEP44](https://tbd54566975.github.io/did-dht-method/#term:bep44) put message with the v value as a [bencode](https://tbd54566975.github.io/did-dht-method/#term:bencode)d DNS packet from the prior step.

Since the encoded size of `v` is capped at 1000, then it can be desirable to compress the DNS packet **before** calculating the beconding.

**Comment by thereisnogabe** [comment]
This is already the case since the DNS packet is compressed using DNS packet encoding, and then the result is bencoded as per BEP44
