### ISSUE TITLE
Clarify the problem that BTC-anchored Gateways are solving

### ISSUE THREAD

**Issue by andresuribe87** [decentralized-identity/did-dht#35]
After multiple reads, I am not sure what problem the gateways are aiming to solve. I _think_ that the problem is "BEP044 establishes that blobs stored in Mainline DHT may expire. This implies that the data backing the DID Document of a did:dht may expire."

And I _think_ a gateway solves it by "Gateways do this work on behalf of DID Controllers, by charging a fee for republishing for a certain amount of time."

Is the above correct?

It would be very useful to readers to understand the motivation behind it.

Some questions below that caused confusion: 
* Where is republishing hasn't been defined?
* What does it mean to "act as a gateway"? The definition of "Gateway" is circular.
* What does "retention" mean? (I think it means republishing).
* Why does the fee need to be timelocked?
* Why does the fee need to be in BTC?
* What happens when the Gateway doesn't re-publish?

**Comment by thereisnogabe** [comment]
the spec has been updated...is this clear now?

**Comment by andresuribe87** [comment]
It's much, much, better thanks!

I think there's room for improvement that explains the motivation behind why it's desirable for client to compute a "retention proof". I suggest something along the lines of

> A gateway is publicly discoverable, and thus any computer that's connected to the internet can ask for the gateway to do work. In order to ensure that there is fairness in the access to the resources that a gateway is publishing, we introduce a mechanism by which gateways can limit the amount of requests that are sent by a single client over a fixed period of time. Retention proof is this mechanism. A Retention Proof is a Proof of Work performed over [...]
