### ISSUE TITLE
Implement caching

### ISSUE THREAD

**Issue by thereisnogabe** [decentralized-identity/did-dht#59]
If a DID is fetched multiple times within a given time window (e.g. 5 min) return the cached DID

**Comment by thereisnogabe** [comment]
Consider using https://github.com/jellydator/ttlcache

**Comment by thereisnogabe** [comment]
A few updates need to be made:

1. Cache on reads in addition to writes (what happens today)
2. Set a memory limit on the cache
3. Gracefully close the cache on shutdown
4. Look into other cache solutions (like https://pkg.go.dev/istio.io/pkg/cache)

cc: @andresuribe87 believe I've captured your feedback here

**Comment by andresuribe87** [comment]
Just a note, that memory limits haven't been covered. In case you want to keep a tracking item.

**Comment by thereisnogabe** [comment]
@andresuribe87 https://github.com/TBD54566975/did-dht-method/pull/63
