### ISSUE TITLE
Update test vectors

### ISSUE THREAD

**Issue by andresuribe87** [decentralized-identity/did-dht#78]
I suggest to update the test vectors so that:
* Did documents have the `@context` property.
* When verification relationships reference an existing verification method, use a URL that starts with a did URL.

If that makes sense, the resulting vectors are below.

### Vector 1

```json
{
  "@context": [
    "https://www.w3.org/ns/did/v1"
  ],
  "id": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo",
  "verificationMethod": [
    {
      "id": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0",
      "type": "JsonWebKey",
      "controller": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo",
      "publicKeyJwk": {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "YCcHYL2sYNPDlKaALcEmll2HHyT968M4UWbr-9CFGWE",
        "alg": "EdDSA",
        "kid": "0"
      }
    }
  ],
  "authentication": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0"
  ],
  "assertionMethod": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0"
  ],
  "capabilityInvocation": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0"
  ],
  "capabilityDelegation": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0"
  ]
}
```

### Vector 2
```json
{
  "@context": [
    "https://www.w3.org/ns/did/v1"
  ],
  "id": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo",
  "verificationMethod": [
    {
      "id": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0",
      "type": "JsonWebKey",
      "controller": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo",
      "publicKeyJwk": {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "YCcHYL2sYNPDlKaALcEmll2HHyT968M4UWbr-9CFGWE",
        "alg": "EdDSA",
        "kid": "0"
      }
    },
    {
      "id": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0GkvkdCGu3DL7Mkv0W1DhTMCBT9-z0CkFqZoJQtw7vw",
      "type": "JsonWebKey",
      "controller": "",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "secp256k1",
        "x": "1_o0IKHGNamet8-3VYNUTiKlhVK-LilcKrhJSPHSNP0",
        "y": "qzU8qqh0wKB6JC_9HCu8pHE-ZPkDpw4AdJ-MsV2InVY",
        "alg": "ES256K",
        "kid": "0GkvkdCGu3DL7Mkv0W1DhTMCBT9-z0CkFqZoJQtw7vw"
      }
    }
  ],
  "authentication": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0"
  ],
  "assertionMethod": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0",
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0GkvkdCGu3DL7Mkv0W1DhTMCBT9-z0CkFqZoJQtw7vw"
  ],
  "capabilityInvocation": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0",
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0GkvkdCGu3DL7Mkv0W1DhTMCBT9-z0CkFqZoJQtw7vw"
  ],
  "capabilityDelegation": [
    "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#0"
  ],
  "service": [
    {
      "id": "did:dht:cyuoqaf7itop8ohww4yn5ojg13qaq83r9zihgqntc5i9zwrfdfoo#service-1",
      "type": "TestService",
      "serviceEndpoint": "https://test-service.com"
    }
  ]
}
```

**Comment by thereisnogabe** [comment]
> Did documents have the `@context` property.

I specifically did not include a `@context` property because this DID Document does not leverage JSON-LD.

> When verification relationships reference an existing verification method, use a URL that starts with a did URL.

Either can work. I don't see a problem with the vectors as-is, do you think differently?

**Comment by andresuribe87** [comment]
> > Did documents have the `@context` property.
> 
> I specifically did not include a `@context` property because this DID Document does not leverage JSON-LD.
> 

While it doesn't leverage JSON-LD, including it is trivial and promotes interoperability with companies that want to use it. Not a big deal, but I do think it's more useful to have it.

> > When verification relationships reference an existing verification method, use a URL that starts with a did URL.
> 
> Either can work. I don't see a problem with the vectors as-is, do you think differently?

I agree either are valid, and can work. That said, I think it's easier to implement verification method resolution when the URL uses the [absolute URL with fragment string](https://url.spec.whatwg.org/#absolute-url-with-fragment-string). 

I've seen implementation bugs because of such use. An example of such is https://github.com/TBD54566975/ssi-service/issues/190

**Comment by thereisnogabe** [comment]
> including it is trivial

I think it opens a can of worms. Until we have clear signals from implementers that _won't_ use did:dht unless there's a context I'm inclined to keep it out.

I'm fine to update the vectors to be fully qualified. I will self assign this issue for that work.
