### ISSUE TITLE
Clarify `secp256k1` VerificationMethod `k` property mapping

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-dht#81]
<img width="850" alt="image" src="https://github.com/TBD54566975/did-dht-method/assets/4887440/105da20a-9837-43b9-b508-52726fa256e7">

For `secp256k1` specifically, given that `k` is is the base64URL [[RFC4648](https://did-dht.com/#ref:RFC4648)] representation of the public key it might be helpful to specify whether `k` is expected to be the compressed, uncompressed, or either and check for both. a compressed EC key can be inflated. `JWK` expects both `x` and `y` to be present for `kty: EC`

**Comment by thereisnogabe** [comment]
the spec states that keys must be represented as a JWK, and the only JWK representation of a secp256k1 key (at present) is [defined here](https://datatracker.ietf.org/doc/html/rfc8812#section-3.1):

> As a compressed point encoding representation is not defined for JWK elliptic curve points, the uncompressed point encoding defined there MUST be used

I can update the registry to make this clear.
