### ISSUE TITLE
Clarify where `base64url` encoding should include padding or not

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-dht#82]
`base64url` encoding is used in a few places e.g.

<img width="854" alt="image" src="https://github.com/TBD54566975/did-dht-method/assets/4887440/fc64d7f9-f2da-4313-bca3-adb06dd95be7">

it might be worth specifying whether the encoded urls should include padding or not especially since `JOSE` expects all base64url encoding to include no padding:

from [section 2](https://datatracker.ietf.org/doc/html/rfc7515#section-2) of the JWS spec:

<img width="865" alt="image" src="https://github.com/TBD54566975/did-dht-method/assets/4887440/7198cdfa-ee90-4c4b-9c8d-2072d8b9d750">

had to accommodate for this [in dart](https://github.com/TBD54566975/tbdex-dart/blob/main/lib/src/extensions/base64url.dart)

**Comment by mistermoe** [comment]
should probably use no padding given that `=` is used to delimit field names and field values in `RData` which. means splitting on `=` wouldn't be possible. [example](https://github.com/TBD54566975/tbdex-dart/blob/did-dht-resolver/lib/src/dids/did_dht.dart#L101)

**Comment by thereisnogabe** [comment]
yes, no padding is used - as you point out if it were used the encoding would break. I can add text to make this clearer.

**Comment by thereisnogabe** [comment]
fixed in #84
