### ISSUE TITLE
Support multiple service endpoints in a single service property

### ISSUE THREAD

**Issue by thereisnogabe** [decentralized-identity/did-dht#85]
> yeah in that case i think `_sN._did.` should absolutely use `;` to separate entities vs. `,` as you have right now because values like `uri` can have multiple values as noted [here](https://www.w3.org/TR/did-core/#dfn-serviceendpoint). 

![image](https://github.com/TBD54566975/did-dht-method/assets/4887440/f1036424-6fce-4066-9023-b32a14234102)

> On that note, did `did:dht` make an explicit decision to not support `serviceEndpoint` being an object? DWNs require this which you can see [here](https://identity.foundation/decentralized-web-node/spec/#service-endpoints)

![image](https://github.com/TBD54566975/did-dht-method/assets/4887440/b6c8a517-a2e0-4007-9984-3df899cf8f60)

_Originally posted by @mistermoe in https://github.com/TBD54566975/did-dht-method/issues/83#issuecomment-1877709738_

**Comment by thereisnogabe** [comment]
My belief is that this risks exceeding the length of a text packet and we should instead encourage multiple service endpoints be used. Open to other opinions / workarounds!

**Comment by mistermoe** [comment]
definitely hear your concern around exceeding text packet length. here's a thought that came to mind.

# Service RData


## Entries

| Entry | Required | Description                             |
| ----- | -------- | --------------------------------------- |
| `id`  | Y        | Service's ID                            |
| `t`   | Y        | Service's Type                          |
| `uri` | N        | List of ServiceEndpoint URIs            |
| `se`  | N        | List of Service Endpoint resource names | 


## Examples

### Single URI
```
id=dwn;t=DecentralizedWebNode;uri=https://whatever.com
```

### Multiple URIs
```
id=someservice;t=SomeService;uri=https://whatever.com,https://ok.com
```

### Service Endpoint
```
id=dwn;t=DecentralizedWebNode;se=se0
```


# Service Endpoint
Each Service Endpoint's name is represented as a `_se0._did.`. RData entries are dynamic

## Example
```
nodes=did:example:host,https://dwn.example.com
```

It doesn't necessarily alleviate length concerns. but it came to mind so i figured i'd toss it out there.

**Comment by thereisnogabe** [comment]
I like the second example, I think we can do something with that.
