### ISSUE TITLE
Consider adding a version of DHT spec being used in the DNS records for a document

### ISSUE THREAD

**Issue by andresuribe87** [decentralized-identity/did-dht#92]
If there is ever a need for another version of the spec, then it would be useful for users to differentiate between them. 

DKIMs and SPF do this. See https://www.cloudflare.com/learning/dns/dns-records/dns-dkim-record/ and https://www.cloudflare.com/learning/dns/dns-records/dns-spf-record/

For DHT, I would suggest adding it as an additional property in the `_did.` TXT record. The first example in https://did-dht.com/#dids-as-dns-records would become the following:

`v=1;vm=k0,k1,k2;auth=k0;asm=k1;inv=k2;del=k2;srv=s0,s1,s2`

**Comment by frankhinek** [comment]
Sounds like a good addition and a simple monotonically increasing integer version seems like a good idea.
