### ISSUE TITLE
Consider designing with DNS TXT record limits in mind

### ISSUE THREAD

**Issue by andresuribe87** [decentralized-identity/did-dht#94]
DNS servers [have](https://support.google.com/a/answer/11613097?hl=en#:~:text=Most%20TXT%20records%20can%20have%20up%20to%20255%20characters.) [limits](https://www.cloudflare.com/learning/dns/dns-records/dns-txt-record/#:~:text=Most%20DNS%20servers%20will%20put%20a%20limit%20on%20how%20big%20TXT%20records%20can%20be%20and%20how%20many%20records%20they%20can%20store%2C). If the goal is to eventually support DNS, then this is important to have those limits mind. The DHT spec could have affordances on the algorithm for splitting data when a record is over 255 chars.

**Comment by thereisnogabe** [comment]
Agree this is good to support!

**Comment by thereisnogabe** [comment]
related to #147
